### ISSUE TITLE
wrong folder address

### ISSUE THREAD

**Issue by JKLEE1015** [intel/edge-developer-kit-reference-scripts#1]
![image](https://github.com/intel/edge-developer-kit-reference-scripts/assets/84305163/ff30231c-d078-4640-9327-b572ec7f9380)

wrong cd edge-developer-kit-reference-scripts/platforms/coreultra/**mtl** 
correct cd edge-developer-kit-reference-scripts/platforms/coreultra/**mtluh**

**Comment by gooishin** [comment]
Thanks! I will take note and fix it soon.

**Comment by gooishin** [comment]
Resolved in main branch
