### ISSUE TITLE
ubuntu 20.04 error

### ISSUE THREAD

**Issue by Chen1129-cloud** [intel/edge-developer-kit-reference-scripts#14]
Ubuntu 20.04 have run ./setup.sh. The OS shoe the error. Please help
![Run error](https://github.com/intel/edge-developer-kit-reference-scripts/assets/67550278/5c032cd3-d87b-4628-9a0f-160c6cf99571)

**Comment by gooishin** [comment]
Hi @Chen1129-cloud, the package libtbb12 only available for Ubuntu 22.04 LTS and above. This MTL setup script is validated on Ubuntu 22.04 LTS, so I recommend install this version. Let me know if you have concern on this.

**Comment by Chen1129-cloud** [comment]
No! It is backward compatible with ubuntu20.04, specified in computer. Only use Ubuntu 20.04 now. Thanks
![image](https://github.com/intel/edge-developer-kit-reference-scripts/assets/67550278/d4f9f164-b900-4bc4-bd82-1b9aecfa9c73)

**Comment by gooishin** [comment]
Hi @Chen1129-cloud, sorry for late response. As we only validated in Ubuntu 22.04, sorry that we are not able to assist you further.
